swagger: "2.0"
main:
  nav:
    text: "SaaSquatch Product News"
    icon: ""
    path: "/product-news"
  nav:
    text: "Integrations"
    icon: ""
    path: "/integrations"
  # success-center:
  #   text: "Success Center"
  #   subtext: "Learn how to use Referral Saasquatch"
  #   icon: ""
  #   sidebar:
  #     back: "main"
  #     nav:
  #       text: ""
  #     learn:
  #       text: "Learn About SaaSquatch"
  #       icon: ""
  #       sidebar: 
  #         nest:
  #           row:
  #             text: "Growth Automation 101"
  #             path: "/growth/ga-101"
  #           row:
  #             text: "Groth Automation Customer Lifecycle"
  #             path: "/growth/customer-lifecycle"
  #           row:
  #             text: "SaaSquatch Frowth Automation Platform"
  #             path: "/growth/saasquatch-ga"
  #           row:
  #             text: "Program Library"
  #             path: "/program/library"
  #           row:
  #             text: "Program Reward Options"
  #             path: "/feature/rewards"
  #           row:
  #             text: "Analytics Overview for Growth Automation Programs"
  #             path: "/success/ga-analytics"
  #     expand:
  #       text: "Learn About SaaSquatch"
  #       icon: ""
  #       sidebar: 
           
  nav:
    text: "JSON Web Tokens"
    icon: ""
    path: "/topics/json-web-tokens"
  nav:
    text: "Testing Best Practices"
    icon: ""
    path: "/developer/testing"
